### ISSUE TITLE
Bug in setup_env.sh script when installing package

### ISSUE THREAD

**Issue by Itschotsch** [MeteoSwiss-APN/mch-python-blueprint#115]
## Issue Summary
There seems to be a bug in the `setup_env.sh` script of the Blueprints. When trying to install a package using the command `tools/setup_env.sh -m -n <name>`, an error occurs stating "Could not solve for environment specs". Upon investigation, it was found that the correct command to create the environment should be `mamba env create -n <name> -f <environment.yml>`, but the current command in `setup_env.sh` is `${CONDA} create -n ${ENV_NAME} python=${PYVERSION} --yes`, which does not include the `env` keyword. This results in the same behavior described in [this GitHub issue](https://github.com/mamba-org/mamba/issues/1145).

## Steps to Reproduce
1. Run the command `tools/setup_env.sh -m -n <name>`.
2. Error message "Could not solve for environment specs" is displayed.

## Expected Result
The package should be installed successfully without any errors.

## Actual Result
The error message "Could not solve for environment specs" is displayed.

## Workaround
The issue can be resolved by running the command `tools/setup_env.sh -m -u -n <name>`.

## Suggested Solution
The `setup_env.sh` script should be updated to include the `env` keyword in the create command, i.e., `${CONDA} env create -n ${ENV_NAME} python=${PYVERSION} --yes`.

## Environment
The issue was observed in the `setup_env.sh` script of the [lm-pyscripts package](https://github.com/MeteoSwiss-APN/lm-pyscripts).
- Date: 14.04.2023
- Copier version: 7.0.1
- Python version: 3.11.0
- Conda version: 22.11.1
- Mamba version: 1.1.0
- OS: SUSE Linux Enterprise Server 15 SP3 (Balfrin)

## Additional Information
The issue has been discussed in [this GitHub issue](https://github.com/mamba-org/mamba/issues/1145).

**Comment by twicki** [comment]
This is solved with the new environment file
