### ISSUE TITLE
Consider/implement conda support

### ISSUE THREAD

**Issue by ruestefa** [MeteoSwiss-APN/mch-python-blueprint#14]
## Background

The blueprint uses the `venv` module to create virtual environments. This is a good approach because it is the standard solution that's built into python. However, it is agnostic to non-python dependencies such as the C libraries geos and proj, which the frequently used package cartopy (map plotting) depends on. This can require workarounds on certain systems (like CSCS) such as installing cartopy from github instead of pypi so it compiles against the installed C libraries.

Conda environments, on the other hand, manage not only python packages, but also non-python dependencies (and even python itself). This would allow to manage libraries like geos and proj directly instead of relying on the system installations.

The reason why it isn't used in the blueprint is simply that it has not been part of it when it was taken over by @ruestefa, and the question never really came up.

## Tasks

- [x] Investigate whether there are any downsides to using conda at CSCS compared to `venv`
- [x] If not, add support to the blueprint (documentation & Makefile etc.)
  - Optimally, retain `venv` as an option and add conda as an alternative, to be chosen during blueprint project creation

## Assignees

Whoever wants to take this over! :)

**Comment by bascrezee** [comment]
@clairemerker Made a great start with this, with your help @ruestefa , thanks for that.  @sadamov Tested succesfully. And also I can confirm that it works great. 

I have one open question. During my migration of the `kenda_python` repository I also had to include the package `apepi` used by @DanielLeuenberger which is installed directly from git. I did not manage to integrate this in `dev-requirements.in`. Installing it afterwards works fine with: 

`pip install -e git+ssh://git@github.com/MeteoSwiss-APN/apepi@v1.1.0#egg=apepi`

When using an environment.yml file, it is easy to use pip and parse options (see e.g. [here](https://github.com/conda/conda/blob/master/tests/conda_env/support/advanced-pip/environment.yml)). Should we consider switching to using an `environment.yml` file in the case one chooses to go for conda installation?

**Comment by ruestefa** [comment]
@bascrezee The syntax to include github packages in requirements files is as follows:

```
apepi@git+ssh://git@github.com/MeteoSwiss-APN/apepi.git@v1.1.0
```

Are you sure, however, that apepi is a development rather than a runtime dependency?

Regarding environment.yml, it's only used by conda and doesn't make sense in a pure pip+venv environment, so I recomment to wouldn't "switch to it" (as in, replace the requirements files) unless a project actually uses conda.

**Comment by bascrezee** [comment]
> git+ssh://git@github.com/MeteoSwiss-APN/apepi.git@v1.1.0



> @bascrezee The syntax to include github packages in requirements files is as follows:
> 
> ```
> apepi@git+ssh://git@github.com/MeteoSwiss-APN/apepi.git@v1.1.0
> ```
> 
> This works fine with unpinned requirements (`requirements*.in`), though I couldn't get it to work with pinned requirements for cartopy and shapely in pyflexplot (probably because of the system dependencies), which was a major reason to take the plunge into conda.

This doesn't work for me. I also tried taking the output of `pip freeze` (after having it installed manually) and pasting this.  When inserting this (note the spaces around the first `@`, they are necessary) in `requirements*.in`: 

```
apepi @ git+ssh://git@github.com/MeteoSwiss-APN/apepi@0a43892468006cf6638a6e534a0ac468dd131873
```

I get: 
```
CondaValueError: could not parse 'apepi @ git+ssh://git@github.com/MeteoSwiss-APN/apepi@0a43892468006cf6638a6e534a0ac468dd131873' in: requirements/requirements.in
```

When using: 
```
apepi@git+ssh://git@github.com/MeteoSwiss-APN/apepi@0a43892468006cf6638a6e534a0ac468dd131873
```

I get: 
```
PackagesNotFoundError: The following packages are not available from current channels:

  - //git@github.com/meteoswiss-apn/apepi@0a43892468006cf6638a6e534a0ac468dd131873
```

To me it seems as if Conda does not understand this syntax, see also [here](https://stackoverflow.com/questions/59864503/direct-link-to-github-in-requirements-txt-while-using-conda).
 
> 
> (Are you sure, however, that apepi is a development rather than a runtime dependency?)

It is a run time dependency, I didn't give that much attention yet, but now make the distinction between runtime and dev dependencies. 
> 
> Regarding environment.yml, it's only used by conda and doesn't make sense in a pure pip+venv environment, so I recomment to wouldn't "switch to it" (as in, replace the requirements files) unless a project actually uses conda.

Yes, agree. I also meant to only use `environment.yml` in case of conda installation.

**Comment by ruestefa** [comment]
> This doesn't work for me

It works with pip, which is what I had in mind (tested with Python 3.8.10 on my laptop):

```
python -m venv venv
source venv/bin/activate
echo 'apepi@git+ssh://git@github.com/MeteoSwiss-APN/apepi.git@v1.1.0' > requirements.in
python -m pip install -r requirements.in
```

However, the `requirements*.in` file indeed isn't usable with conda (`conda create -p test --file requirements.in`)... Looks like conda cannot directly install packages from github (see [here](https://stackoverflow.com/a/32799944/4419816)), only with pip inside conda (which isn't ideal for dependencies because conda isn't aware of those packages). The cleanest solution would be to somehow add apepi to a conda channel so it can be installed regularly (like uploading it to pypi to make it available to pip), but no idea how to do that.

Maybe the best approach for conda would be to switch to `environment*.yml` files analogous to the `requirements*.in`/`requirements*.txt`, i.e., to specify the unpinned requirements in a file like `environment-unpinned.yml` (just making up names now), in which github packages to be installed with pip could be specified as described in the linke above. That would lead to some duplication for packages that support both venv+pip and conda, but that's probably not a big problem in practice as a given package will likely always be installed with one or the other.

**Comment by ruestefa** [comment]
This can be closed as conda as the switch to conda is history.
