### ISSUE TITLE
Add templates for sphinx documentation

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/mch-python-blueprint#30]
### Description

For adding documentation pages, a standard in python is to compile rst or md with sphinx. 
Then there could be two options to publish the pages. Github IO pages, and readthedocs. 
For github IO pages, we will need a github actions that compiles all the doc with sphinx and pushes to github. See for example: 
https://github.com/C2SM/spack-c2sm/blob/master/.github/workflows/default.yml

For readthedocs, one does only need to register the repo, and have a config file. See for example: 
https://github.com/pydata/xarray/blob/main/.readthedocs.yaml

### Further ideas ?
* Functionality to compile rst, but also the code documentation (API). xarray uses the autosummary of sphinx for compiling code documentation: 
https://github.com/pydata/xarray/blob/main/doc/api.rst
* Add a theme. xarray uses the book theme from jupyter notebooks (sphinx_book_theme). See https://github.com/pydata/xarray/blob/main/doc/conf.py
* sphinx-quickstart gives an easy way to start with a basic configuration for sphinx doc/conf.py
* add a badge to the README for a quick link to the doc

**Comment by ruestefa** [comment]
Related: #11

**Comment by ruestefa** [comment]
Closing #11 as this issue will address that implicitly.

**Comment by regDaniel** [comment]
First version implemented with #32, will revisit for #55 .

**Comment by regDaniel** [comment]
implemented in #76 and #79
