### ISSUE TITLE
Merge setup.py into pyproject.toml

### ISSUE THREAD

**Issue by regDaniel** [MeteoSwiss-APN/mch-python-blueprint#37]
### Description

Add a template for `setup.cfg` to ensure reproducible behaviour across machines, GitHub actions, etc. and adapt `setup.py` accordingly.

### What I Did

@bascrezee had diverging behaviours when running flake8 locally and through precommit on GitHub actions.

**Comment by bascrezee** [comment]
The diverging behaviour is explained by the fact that I called `flake8` in a different way. Using `pre-commit run --all-files` (as in the github actions workflow) gives the same behaviour.

**Comment by regDaniel** [comment]
Move to `pyproject.toml`. This would include removal of `setup.py` and creating a `flake8` config file as flake 8 does not yet accept the new standard.

**Comment by ruestefa** [comment]
> Move to pyproject.toml. This would include removal of setup.py and creating a flake8 config file as flake 8 does not yet accept the new standard.
Changed title accordingly.

**Comment by ruestefa** [comment]
Turns out the `flake8` config can also be put in `pyproject.toml` if the package `flake8-pyproject` is installed (temporary fix until `flake8` supports `pyproject.toml` natively, whenever that may be).

**Comment by ruestefa** [comment]
Done successfully in #48.
