### ISSUE TITLE
Check which configuration files impact the behaviour of `pre-commit` 

### ISSUE THREAD

**Issue by bascrezee** [MeteoSwiss-APN/mch-python-blueprint#40]
When running `pre-commit run --all-files` it seems that parts of the configuration (either in `tox.ini` , `setup.cfg` and `.pre-commit-config.yaml`) do not have effect. For example it was noted that Flake8 exclude in setup.cfg has no effect, at least not when pre-commit-config has excludes for Flake8.

**Comment by ruestefa** [comment]
Quote from @bascrezee in #37:

> The diverging behaviour is explained by the fact that I called flake8 in a different way.

With this, can this issue be closed?

**Comment by bascrezee** [comment]
> Quote from @bascrezee in #37:
> 
> > The diverging behaviour is explained by the fact that I called flake8 in a different way.
> 
> With this, can this issue be closed?

Yes :)
