### ISSUE TITLE
Detach Github Repository from cookiecutter

### ISSUE THREAD

**Issue by regDaniel** [MeteoSwiss-APN/mch-python-blueprint#66]
Currently we fork from [cookiecutter](https://github.com/audreyfeldroy/cookiecutter-pypackage) but our new blueprint does not have a lot in common with this repository. Therefore we should detach it.

**Comment by ruestefa** [comment]
Yes, of course, once cookiecutter is dead and buried.

**Comment by cosunae** [comment]
we are close to a final merge, so I have requested already the detach
