### ISSUE TITLE
Version restrictions across multiple requirements files not respected

### ISSUE THREAD

**Issue by ruestefa** [MeteoSwiss-APN/mch-python-blueprint#86]
YAML files were developed for complete environments, so `conda env` can only deal with one YAML file at a time and distributing requirements across multiple YAML files (like `requirements.yml` and `dev-requirements.yml`) requires some workarounds (like `conda env update`), which introduce some subtle issues that I just stumbled upon.

Usually, `conda env create -n foo -f requirements.yml -y && conda env update -n foo -f dev-requirements.yml` achieves the desired result, which is a dev env that contains up-to-date versions both the runtime and the dev deps. However, in this sequence of commands, the version restrictions in `requirements.yml` are not respected by `conda env update`, but can be overridden by the solver, which is not acceptable.

Potential solutions:

1. Switch the order, i.e., first install the dev deps and on top of those the run deps.
  - Pro: The version restrictions of the run deps are respected.
  - Con: Those of the dev deps may be overridden instead.

2. Move the dev deps into `requirements.yml` and remove `dev-{requirements,environment}.yml`
  - Pro: All versions are restricted, and managing dependencies becomes less complex. Plus, dev reqs can still be separated w/i the file by a comment.
  - Con: Dev deps are also installed in production envs.

3. Copy the run deps into `dev-requirements.yml`
  - Pro: All version restrictions are always respected.
  - Con: The run deps in the two `*requirements.yml` are bound to diverge at some point.

4. Use a third-party tool like [conda-merge](https://github.com/amitbeka/conda-merge) (to be called in `setup_env.sh`), which merges multiple YAML requirements files into one
  - Pro: Achieves exactly what we want: Dev and run reqs are kept separate but all version restrictions are always respected
  - Con: Adds an additional dependency on a third-party tool.

On balance, the best solution might be (2), i.e., to eliminate the separation between dev and run reqs and envs (other than by separating then with a comment in `requirements.yml`), as this ensures that version restrictions are always respected and that dev and prod envs are consistent (even identical). I suspect the fact that dev deps would also be installed in prod envs would be a minor concern at best in practice (or even a benefit when testing a new installation). Simplifying dependency management (like `setup_env.sh`) would be an added bonus.

Thoughts?

**Comment by regDaniel** [comment]
Good one. And again more fiddly than we thought. I would primarily consider the following two options:

- What you seem to prefer @ruestefa: We just drop the separation of prod and dev environment. The overhead in terms of memory usage is marginal compared to the amount of TB we push around in production. Also I would not expect too many conflicts between dependencies of the dev libraries and dependencies of the prod libraries as most conflicts we've seen so far were in rather domain-specific packages such as `xarray` and `cfgrib`. Therefore, the cons of settling with one environment do not outweigh the pros in my opinion.
- The bricolage solution (would be 3.5 in your list I guess): If the user goes for a dev installation, we just cat the lines of `dev-environment.yml` and `environment.yml` to a new (temporary) file, install from this one and then remove it again. Clearly, this will create an overhead in terms of code in the blueprint and might be a nightmare to debug if you do not immediately see what happens under the hood as a user.

I'd prefer the first option. @cosunae and @clairemerker thoughts?

**Comment by ruestefa** [comment]
> Also I would not expect too many conflicts between dependencies of the dev libraries and dependencies of the prod libraries

Actually these are exactly the cases when prod version restrictions are overridden b/c the already installed versions cannot satisfy the constraints requested by the dev dependencies and you end up with wrong versions of prod deps in the dev env. So you really want to catch and resolve those conflicting situations.

_(I specifically ran into this problem (which led me to discover this issue) because one of my conda projects depended on `typer>=6.x` (because I just put the current version as the minimum requirement when starting to work on that project), but `rstcheck` in `dev-requirements.yml` depends on `typer<5`, so the most recent version of my conda project was replaced by an old version w/o that typer requirement when installing the dev dependencies, even though I requested its latest version in `requirements.yml`.)_

> we just cat the lines of dev-environment.yml and environment.yml to a new (temporary) file

I purposefully didn't suggest any solution involving more custom scripting as that tends to introduce more problems than it solves (lesson learned). Also, `cat`-ing the YAML files together isn't trivial, but it's actually exactly what conda-merge does, so your suggestion really boils down to (3).

**Comment by regDaniel** [comment]
> I purposefully didn't suggest any solution involving more custom scripting as that tends to introduce more problems than it solves (lesson learned).
Fully agree.

> So you really want to catch and resolve those conflicting situations.
Sorry, I was not precise here. In the past, we had conflicts between dependencies that were not resolvable with conda. But I do not expect that to happen between dev dependencies and prod dependencies as the libraries in the dev dependencies are usually fairly well maintained. I do however fully agree that these conflicts should be resolved and that the prod dependencies must not be overwritten in the dev env.

**Comment by ruestefa** [comment]
> Sorry, I was not precise here. In the past, we had conflicts between dependencies that were not resolvable with conda.

I think I understood you correctly; these situation do have to be resolved somehow by adjusting the version restrictions or installing one of the packages with pip instead of conda. If that is not possible, then the dev env resulting from the current two-step installation procedure is simply wrong. (And if it's not possible at all, then that's another issue.)

**Comment by ruestefa** [comment]
I've implemented the unified requirements in my blueprint version and created a PR (#87) in case you decide to adopt this.

**Comment by ruestefa** [comment]
Meanwhile, I've implemented this in my forked blueprint and applied it to the projects that use it. Because I performed the merge of `requirements/dev-requirements.yml` into `requirements/requirements.yml` and the move of `requirements/requirements.yml` and `requirements/environment.yml` in one go, copier was in a bit over its head and lost track the adapted contents of `requirements.yml`, so I ended up quickly doing the merge-and-move manually before updating copier in each project:

```bash
cat requirements/env-requirements.yml >> requirements/requirements.yml
vim requirements/requirements.yml  # merge contents
git add requirements/requirements.yml
tools/setup_env.sh -m -u -e
git add requirements/environment.yml
git rm -f requirements/dev-{requirements,environment}.yml
git commit -m "merge dev-requirements into requirements"

git mv requirements/{requirements,environment}.yml .
rmdir requirements
git commit -m "move requirements and environment files into root"

copier -f update
# stage changes, resolve conflicts
git commit -m "run copier update"
```

Doing the merge and move in separate copier updates would likely reduce the manual work a bit, since custom requirements could then be handled during the staging process following `copier -f update` (with `git add -p` etc.) instead of manually before the copier update, but the above approach is also pretty straightforward.
