### ISSUE TITLE
Commit hashes in environment

### ISSUE THREAD

**Issue by regDaniel** [MeteoSwiss-APN/mch-python-blueprint#96]
blueprint v. 0.2.0

### Description

The exported environments in the `tmpl` folder contain commit hashes. However when the export env option of `setup_env.sh` is used there are no commit hashes in the environment files. This leads to unnecessarily large changes when pushing the environment file. We can probably exclude the commit hashes. Check if this is fixed by #88 or #87 .

**Comment by huppd** [comment]
I think this is also coverd in https://github.com/MeteoSwiss-APN/mch-python-blueprint/pull/92

**Comment by regDaniel** [comment]
Yep, it was covered by #92 .
